### ISSUE TITLE
With code translation creates unreadable code

### ISSUE THREAD

**Issue by tverweij** [icsharpcode/CodeConverter#520] opened 2020-02-05 19:23 UTC
### Steps to reproduce
**Example VB code:**

With MyObject
    . x = 10
    . y = 20
    with MyObject.MyProperty
        .q = 6
        .w = 7
    end with
end with

**translates to the following C# code:**
{
    {
        var withBlock = MyObject;
        withBlock.x = 10;
        withBlock.y = 20;
        {
            var withBlock1 = MyObject.MyProperty;
            withBlock1.q = 6;
            withBlock1.w = 7;
        }
    }
}

**A better translation (better readable code) should be:**
{
    MyObject.x = 10;
    MyObject.y = 20;
    {
        MyObject.MyProperty.q = 6;
        MyObject.MyProperty.w = 7;
    }
}

**Comment by GrahamTheCoder** [comment] 2020-02-05 22:53
Hi, thanks for getting in touch. 
I'm afraid that's the intended behaviour. I agree your suggestion is more readable, but the it behaves differently if MyObject.MyProperty has any side effects (e.g. It might now write to the console twice instead of once)

So the default is to introduce a variable, and then in some cases where we can be sure it's safe (or where introducing a variable would itself change behaviour), avoid doing so. I made a few improvements around this recently which will be released shortly (also similar for switch statements) but I'll leave this issue open since there's more to do.

If you use extensions like code cracker, roslynator or resharper, there's an automated refactoring to Inline temporary variables, but applying it case by case is tedious I agree!

**Closed** 2020-02-18 09:06 UTC
Labels: UX feedback, VB -> C#, enhancement
