### ISSUE TITLE
VB -> C#: Hex conversion gets C removed incorrectly

### ISSUE THREAD

**Issue by cslgyorgy** [icsharpcode/CodeConverter#723] opened 2021-05-13 16:21 UTC
### Input code
Dim g= New Guid(&H540B947E, &H8B40, &H45B**C**, &HA8, &HA2, &H6A, &HB, &H89, &H4**C**, &HBD, &HA2)

### Erroneous output
 var g = new Guid(0x540B947E, 0x8B40, 0x45B, 0xA8, 0xA2, 0x6A, 0xB, 0x89, 0x4, 0xBD, 0xA2);

### Expected output
 var g = new Guid(0x540B947E, 0x8B40, 0x45B**C**, 0xA8, 0xA2, 0x6A, 0xB, 0x89, 0x4**C,** 0xBD, 0xA2);

### Details
False Guid converted.

**Comment by GrahamTheCoder** [comment] 2021-05-15 15:12
Oh dear, should be easy enough to fix. I'll try to have a look soon

**Comment by GrahamTheCoder** [comment] 2021-05-15 15:25
I can't reproduce the error in the latest version. I believe the issue was fixed in https://github.com/icsharpcode/CodeConverter/commit/5547b59e8b1c903ca25b44d3b00fba23552a7b2d#diff-8b4f8dd4ffd9cbb5fce4cc8cb2092c1861771120670312493ed0d46f4bb5798c

Please update to a version 8.1.7+, the web converter is always on the latest version of course: https://codeconverter.icsharpcode.net/

Reopen this and let me know if you're still seeing the issue after updating. Thanks!

**Closed by GrahamTheCoder** 2021-05-15 15:25 UTC
Labels: VB -> C#, duplicate, output logic error
