### ISSUE TITLE
convert and copy to clipboard for vsix

### ISSUE THREAD

**Issue by mutigozel** [icsharpcode/CodeConverter#37] opened 2018-03-07 14:03 UTC
Please, bring back convert and copy to clipboard behavior back for vsix. 
It was more useful with the exception message box. Showing exception in output window is not better too.

**Comment by GrahamTheCoder** [comment] 2018-03-08 08:46
Thank you for the feedback. There are some specific reasons this was changed to the output window:
* People don't always know they can press ctrl+c on the error dialog to copy the error and report a bug.
* For multi file conversions:
  * Progress can be shown so the user knows something is happening and doesn't try to start the conversion again.
  * Space to show multiple different errors, allowing partial success rather than an all or nothing scenario.

Can you tell me more about how you use the tool that makes copying to clipboard so useful (compared to opening a file with the text selected)?

And can you tell me more about the problem caused by using the output window that's alleviated by the message box?

**Comment by mutigozel** [comment] 2018-03-08 09:30
Hi Graham, 

Recently started to convert a large project that has like more than 200k of VB code to CS. Among with the conversion we are dividing major namespaces included in one VB project to different CS projects. Transition of the code is not straightforward as convert project to CS automatically. It is a gradient transition as parts of code is converted while the VB codes are constantly maintained/debugged.

As steps of transition, first I check all methods/properties using copy to clipboard. Success if no exception screen popped, while popping a message is a better alert-er to a human. One can easily see where is not converted for a reason. 

For example, sql like linq are not converted and lead to exception window. Some may think that it is something needed to be handled by the converter codes. But we use it as a measure of quality of VB code. Putting TODO s on top of that to have somebody convert them to linq extension functions... Using linq extensions will lead to better performance ... ... and so on with the dots.

Luckily enough I kept the old vsix on my computer. Uninstalled the new extension. Put windows to plane mode (to disable automatic extension update). Installed the old one. Checked off the automatic update option. Continued to use the old one.

As a suggestion of my side. Current behavior is useful you may keep it but bring the old behavior back by adding another context menu item for people that use it like we do. And please bring the exception popup. I constantly keep output window closed.

Regards,

Muti

**Comment by GrahamTheCoder** [comment] 2018-03-08 10:54
I think I understand how you're currently working. I was anticipating that someone in your scenario might do something like this:
* Click a single convert button on the project and receive a single list of which files succeeded and failed (along with reasons)
* Go through the list adding any TODOs by going through that list
* Delete (or git reset) any files created that you don't want, commit any that you do.

Could you explain a bit more which part of that doesn't work for you?
I'm also interested to know where you paste the converted code from the clipboard in order to check it

Somewhat off topic - but you might find this post relevant: [.NET LINQ query syntax vs method chain
](https://stackoverflow.com/a/3776588/1128762)

**Comment by GrahamTheCoder** [comment] 2018-03-22 23:11
Since you have a workaround, and wouldn't want the new version due to its sql-like-linq conversion I've decided not to go in this direction - especially since I can't understand the use case. I'll close the issue until someone else requests it, but it's open to further comments. Thanks for the feedback 👍

**Comment by mutigozel** [comment] 2018-03-26 08:38
After your comments, I forced myself to adopt. Installed the new version, managed myself for the new kind of how things done.

Still think that convert and copy to clipboard would be a good option for fast code conversion checking without messing with the already present code files.

**Comment by GrahamTheCoder** [comment] 2018-03-26 12:28
Thanks for the update Muti, it's good to hear you're able to use the new version 😄 
You mentioned "already present code files". Are you saying that you already have a converted output in the place the converter writes the files (from another converter or something)? For the individual file/snippet conversion, I considered opening a Visual Studio code window with the result without saving it anywhere, or adding an options page (in Tools > Options > Code Converter) to choose a template for the destination file path. Would that be any better for you?

**Comment by GrahamTheCoder** [comment] 2018-05-01 22:35
![image](https://user-images.githubusercontent.com/2490482/39496874-5d6200a2-4d98-11e8-9d15-46e0f31291fa.png)

**Closed** 2018-05-03 09:02 UTC
Labels: UX feedback

**Comment by GrahamTheCoder** [comment] 2018-05-08 00:34
@mutigozel I have added this option back in for you. It's not exactly the same as the old behaviour, but I hope it will help you

**Comment by mutigozel** [comment] 2018-05-08 06:53
Thanks a lot @GrahamTheCoder . Sure it will bring better user interaction for those who only need a quick conversion review rather than complete conversion.
