### ISSUE TITLE
C# -> VB: Deletes Comments on conversion

### ISSUE THREAD

**Issue by FelixFifi** [icsharpcode/CodeConverter#410] opened 2019-11-11 11:30 UTC
### Input code
```C#
/// <summary>
/// test1
/// </summary>
public partial class CSharpClass
{
    // test2
    private int a = 0;
}
```

### Erroneous output
```vbnet
Public Partial Class CSharpClass
    Private a = 0
End Class

```

### Expected output
```vbnet
''' <summary>
''' test1
''' </summary>
Public Partial Class CSharpClass
    ' test2
    Private a = 0
End Class

```

The direction VB -> C# works as expected.

### Details
* Product in use: both
* Version in use: 7.2.0.0

**Comment by GrahamTheCoder** [comment] 2019-11-11 18:39
Thanks, your vote for fixing this has been noted, though I'm closing as a duplicate of #8 and will track progress there. I long ago made a start on this with #32 but there are lots of edge cases to handle. At some point I'll see if I can descope the edge cases and just get some of the common cases working and tested

**Closed** 2019-11-11 20:03 UTC
Labels: C# -> VB, duplicate
