### ISSUE TITLE
C# -> VB: #if ignored

### ISSUE THREAD

**Issue by jdmichel** [icsharpcode/CodeConverter#249] opened 2019-03-01 00:09 UTC
Any c# code in between #if #endif sections is ignored if the expression evaluates to false. 
When porting the project it may be configured to build any number of ways depending on which preprocessor symbols are defined. Maybe Roslyn always preprocesses the files, and therefore ignores everything. Hopefully there is some way to turn that off, because otherwise you'd have to perform the conversion any number of times to catch every case which would be very complex.

**Comment by jdmichel** [comment] 2019-03-01 00:10
Any c# code in between #if #endif sections is ignored.

**Comment by GrahamTheCoder** [comment] 2019-03-01 09:55
Thanks for the report. You're right that Roslyn preprocesses things. I haven't looked deeply into turning it off but I'm unaware of one. I'll close this as a duplicate of #15. Please feel free to upvote that issue. If you find any useful details that might help get Roslyn to show the full information, let me know. The problem I imagine is there would be a separate syntax tree for each different possible combination of compile time constants - they'd need to be each converted, then merged somehow.

**Closed by GrahamTheCoder** 2019-03-01 09:55 UTC
