### ISSUE TITLE
VB -> C#: A conversion error occurred when tracking a control using the event's "sender" parameter

### ISSUE THREAD

**Issue by FiveBushelsOfRice** [icsharpcode/CodeConverter#1072] opened 2024-01-10 07:53 UTC
### VB.Net input code
We want to control the appearance of a set or class of combo boxes or respond to some behavior by writing a combo box click event
```VB.Net
Private Sub TextBox_ComName_Click(sender As Object, e As EventArgs) Handles ComboBox_AreaName.Click
    sender.DroppedDown = True    
End Sub
```
The reason for using the event's "sender" parameter instead of the control name is that we want to control multiple controls at the same time with just one event

### Erroneous output
```C#
private void ComboBox_AreaName_Click(object sender, EventArgs e)
{
    sender.DroppedDown = (object)true; 
}
```
Compiler Error CS1061:'type' does not contain a definition for 'name' and no accessible extension method 'name' accepting a first argument of type 'type' could be found (are you missing a using directive or an assembly reference?).

### Expected output
will be referenced by multiple combo box click events
```C#
private void ComboBox_AreaName_Click(object sender, EventArgs e)
{
    ComboBox combo = (ComboBox)sender;
    combo.DroppedDown = true; 
}
```

### Details
* Product in use: e.g. [icsharpcode.github.io/CodeConverter](https://icsharpcode.github.io/CodeConverter/) / VS extension / both
* Version in use: e.g. 5.6.3 or a commit hash (if it's a 3rd party tool using this library, try one of the above)
* Did you see it working in a previous version, which?
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment] 2024-01-28 18:58
Thanks for the report, sorry I missed the notification. I'll close this as a duplicate of https://github.com/icsharpcode/CodeConverter/issues/1071 and give any updates there

**Closed** 2024-01-28 18:58 UTC
Labels: VB -> C#
