### ISSUE TITLE
VB -> C#  Parameterized property

### ISSUE THREAD

**Issue by vfle** [icsharpcode/CodeConverter#200] opened 2018-11-09 09:43 UTC
### Input code
```vbnet
        Public ReadOnly Property FullName(ByVal lastNameFirst As Boolean) As String
            Get
                If lastNameFirst Then
                    Return LastName & " " & FirstName
                Else
                    Return FirstName & " " & LastName
                End If
            End Get
        End Property
```

### Erroneous output
```C#
        public string FullName
        {
            get
            {
                if (lastNameFirst)
                    return LastName + " " + FirstName;
                else
                    return FirstName + " " + LastName;
            }
        }
```

### Expected output
```C#
        public string  FullName(bool lastNameFirst)
        {
                if (lastNameFirst)
                    return LastName + " " + FirstName;
                else
                    return FirstName + " " + LastName;
        }
```

### Details
Product in use: VS extension

Version in use: 6.1.0.0

**Comment by GrahamTheCoder** [comment] 2018-11-09 16:00
Thanks for the report. Looks like a duplicate of #197 for which the fix was just merged.
It'll be released in the next couple of weeks.

**Comment by vfle** [comment] 2018-11-12 10:05
Sadly all i can help with is identify and workarounds.

Speaking of which, in case anyone else wants to change it before converting it to C# here is a regex to identify the parameterized properties.

`Property?\s+(\w+)\s*(\([^()]+\))`

**Comment by knodel12** [comment] 2018-11-13 19:05
@GrahamTheCoder The only thing that gets odd about this is the setter.  It impossible in C# to call a function and immediately assign something to the result of the function.

For example, if I have a property such as:

```
Private Readonly dict As New Dictionary(Of String, Boolean)()
Public Property Test(str As String) As Boolean
    Get
        Return dict(str)
    End Get
    Set
        If Not dict.ContainsKey(str) Then
            dict.Add(str, False)
        End If
        dict(str) = Value
    End Set
End Property
```

How does the set block work?  C# can call this property, but they have to call it through the implicit functions created in VB (in this case it would be get_Test and set_Test).  I suppose we could swap this out with two overloads, one that takes in the value, one without.  The one that takes in the value would be a sub while the one that doesn't would be a function.  Any references to a property that has a parameter and is set would then have to be switched to a function call rather than a property set.

**Comment by knodel12** [comment] 2018-11-13 19:09
My mistake... It is actually possible to call a function and set the underlying value... It doesn't work for the case above though in C# and it's only supported in C# 7.3 (I believe)

Example C# code:
```
void Main()
{
	Test() = 5;
	Test().Dump();
}

private int underlyingTest = 0;
ref int Test()
{
	return ref underlyingTest;
}
```

**Comment by GrahamTheCoder** [comment] 2018-11-13 21:00
Nice investigation. Yep I usually look at the decompiled IL version of a VB assembly using the feature to see if I can at least take some inspiration. Obviously it doesn't always map across nicely though. Since the setter sounds like a complicated (and not super-common) case, I'd happily take a PR that only works in C# 7.3+ if you can get it working. ref sounds like a plausible way to keep it working.

**Closed** 2019-08-01 01:19 UTC
Labels: VB -> C#
