### ISSUE TITLE
VB -> C#: Alternate Return Syntax in VB Not Converted Correctly

### ISSUE THREAD

**Issue by knodel12** [icsharpcode/CodeConverter#206] opened 2018-11-13 19:21 UTC
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```VB
    Public Function Test() As Integer
        Test = 5
        Console.WriteLine("I planned this!")
    End Function
```

### Erroneous output
```C#
public int Test()
{
    Test = 5;
    Console.WriteLine("I planned this!");
}
```

### Expected output
```C#
public int Test()
{
    int Test;
    Test = 5;
    Console.WriteLine("I planned this!");
    return Test;
}
```

### Details
Product in use: both

Version in use: 6.1.0

Probably going to be a hard one to solve, but I'm documenting it anyway... In VB, if you assign to the implicit variable named the same thing as the function itself, then that variable implicitly becomes a return at the end.  As you can see here, VB implicitly created a variable called Test in the function Test and assigning to that is actually the same as creating a local variable, assigning a value to that, and then returning that local variable.  It's very important to note that it doesn't return until the end.  The console will get written to in this example.

**Comment by GrahamTheCoder** [comment] 2018-11-13 23:56
I think this is a duplicate of https://github.com/icsharpcode/CodeConverter/issues/103

**Closed** 2018-11-13 23:57 UTC
Labels: duplicate
