### ISSUE TITLE
Use Azure Functions Implementation of Code Converter

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/CodeConverter#625] opened 2020-09-10 10:53 UTC
Available APIs:
* https://dotnet-codeconverter.azurewebsites.net/api/Version 
* https://dotnet-codeconverter.azurewebsites.net/api/Convert

This is hosted on the ic#code Azure account (not my personal one; it is a free one that comes with 1m calls). CORS is enabled.

What could we do with it? Tell users to use that backend when actually using the Web API (not the one that comes with the current Web frontend), or maybe switch the existing Web frontend to a pregeneration framework and host as static while calling this backend API.

![cconazure](https://user-images.githubusercontent.com/344208/92719965-3930cc80-f364-11ea-80d9-0e5c6498fdca.png)

**Comment by GrahamTheCoder** [comment] 2020-09-10 21:56
Might be worth trying hooking the ui to it and then publishing the ui as a static site via github pages.

**Comment by GrahamTheCoder** [comment] 2020-09-10 21:59
Theoretically the ui could have a dropdown to allow trying out different versions (mainly useful for reproducing regressions)

**Comment by christophwille** [comment] 2020-09-11 19:01
Yes, hosting statically on GH pages would be a good idea.

**Comment by GrahamTheCoder** [comment] 2020-09-13 13:08
I've started a draft PR #627 moving to a static site using the default VS template.
It needs more tidying, but runs locally now for me so I thought I'd mention it in case that unblocks any testing you wanted to do.
Note: I haven't hooked up to the azure function endpoint yet.

**Comment by GrahamTheCoder** [comment] 2021-12-23 02:22
I've now set the deployed azure function as the default endpoint for a release build (and it's currently running that way in production - though due to some odd caching, some users may need a hard refresh to get the newest version)

**Closed by GrahamTheCoder** 2021-12-23 02:22 UTC
Labels: enhancement, help wanted
