### ISSUE TITLE
Large designer files crash converter (within VS) during formatting

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#778] opened 2021-10-21 17:01 UTC
### Steps to reproduce
1. convert solution
2. crash in phase 1 of 2 converting forms

### Error message shown
* Office\COGuiCommon\IdentArtikel\IdentArtikelForm.Designer.vb - conversion started
* Office\COGuiCommon\Tourenplan\TourenplanForm.Designer.vb - conversion succeeded
* Office\COGuiCommon\Vertraege\VertragsMaschinenHinzufuegen\VertragsMaschinenHinzufuegenForm.Designer.vb - conversion started

Error while formatting and converting comments: System.InvalidOperationException: Exception of type 'System.InvalidOperationException' was thrown.

Error while formatting and converting comments: System.InvalidOperationException: Exception of type 'System.InvalidOperationException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.VerifyIntegrity()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.GreenNode.GetAnnotations()
   at Microsoft.CodeAnalysis.GreenNode.HasAnnotation(SyntaxAnnotation annotation)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.AnalyzeWhitespacesInTrivia(SyntaxTrivia trivia, AnalysisResult& result)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Analyze(SyntaxTriviaList list, AnalysisResult& result)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.Analyzer.Leading(SyntaxToken token)
   at Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.CreateLeadingTrivia(SyntaxToken token)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetOriginalTriviaData(TokenData token1, TokenData token2)
   at Microsoft.CodeAnalysis.Formatting.TokenStream.GetColumn(TokenData tokenData, Func`3 triviaDataGetter)
   at Microsoft.CodeAnalysis.Formatting.FormattingContext.AddAnchorIndentationOperation(AnchorIndentationOperation operation)
   at Roslyn.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source, Action`1 action)
   at Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.Format(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormattingService.Format(SyntaxNode node, AnalyzerConfigOptions options, IEnumerable`1 formattingRules, SyntaxToken token1, SyntaxToken token2, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.FormatIndividually(SyntaxNode node, AnalyzerConfigOptions options, IEnumerable`1 rules, IList`1 spansToFormat, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.Format(SyntaxNode node, IEnumerable`1 spans, Boolean shouldUseFormattingSpanCollapse, AnalyzerConfigOptions options, IEnumerable`1 rules, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Formatting.Formatter.GetFormattingResult(SyntaxNode node, IEnumerable`1 spans, Workspace workspace, OptionSet options, IEnumerable`1 rules, CancellationToken cancellationToken)
   at ICSharpCode.CodeConverter.Shared.OptionalOperations.Format(SyntaxNode node, Document document)
   at ICSharpCode.CodeConverter.Shared.OptionalOperations.MapSourceTriviaToTargetHandled[TSource,TTarget](TSource root, TTarget converted, Document document)

### Details
* Product in use: e.g. VS extension 
* Version in use: 8.4.1.0
* Did you see it working in a previous version, which? no

**Comment by KunzeAndreas** [comment] 2021-11-10 12:11
After splitting crashing assembly it works

**Comment by GrahamTheCoder** [comment] 2021-11-10 12:44
Thanks for letting me know, glad it's working.

I think the outcome here is that I (or indeed anyone) should try to reproduce this bug using just the roslyn API here and submit it as an issue upstream:
https://github.com/icsharpcode/CodeConverter/blob/0c39437a1937283664cc3481c3faf9a9bf4b8854/CodeConverter/Shared/OptionalOperations.cs#L47-L48

I did previously (separately) log the bug upstream of the fact that VS intentionally hard crashes when various things go wrong:
https://github.com/dotnet/roslyn/issues/41724
At that time I had a workaround, to avoid the hard crahses, but it may need a rework after their improvements in https://github.com/dotnet/roslyn/pull/48367

**Comment by GrahamTheCoder** [comment] 2021-12-23 02:23
In #774 I've made a change to decrease the amount of boilerplate for events in many common cases. Hopefully this will help mitigate the issue until a fix can be found

**Comment by GrahamTheCoder** [comment] 2022-04-23 21:33
Ah whoops I've left a duplicate of this. Consolidating this into #877

**Closed by GrahamTheCoder** 2022-04-23 21:33 UTC
