### ISSUE TITLE
Visual Studio crashes during conversion process

### ISSUE THREAD

**Issue by GeoffreyCallaghan** [icsharpcode/CodeConverter#484] opened 2020-01-10 21:07 UTC
I'm trying to convert a C# project to VB. At first I tried to convert the whole solution, but after converting a few files, Visual Studio just crashed and disappeared. 

In the Event Viewer, I see this error (there's more detail, but this is the last thing I see): 
Message: System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.InferredFieldInitializerSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.NamedFieldInitializerSyntax'.
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindObjectInitializer(ObjectCreationExpressionSyntax objectCreationSyntax, TypeSymbol initializedObjectType, BoundWithLValueExpressionPlaceholder asNewVariablePlaceholderOpt, DiagnosticBag diagnostics)

I tracked down an individual file that caused a crash, and commented out code until I found the offending code: 

`var textRect = new Rectangle
                {
                    X = markRect.Right + c_MarkPadding,
                    Y = r.Y,
                    Width = r.Right - markRect.Right - c_MarkPadding,
                    Height = r.Height
                };`

It seems to be the variable 'r', which is just a reference to another Rectangle. 

Any ideas why the converter would have such a drastic error on something like this? 

Thanks in advance, 
Geoff Callaghan

**Comment by GrahamTheCoder** [comment] 2020-01-11 11:08
Apologies for this, I've seen and fixed a similar bug recently, but didn't realise it'd ever been released. I'll check the test case you provided and get the fix out ASAP. Thanks!

**Comment by GrahamTheCoder** [comment] 2020-01-11 11:51
The bug isn't fixed on master. The reason Visual Studio crashes is:
* I've called the Microsoft.CodeAnalysis library to "simplify" the code, i.e. cut out redundant code. 
* It tried to replace a node with something invalid for the position.
* The Microsoft.CodeAnalysis library either accidentally or intentionally kills the process without ever firing reaching my surrounding catch block. I suspect it was accidental due to failing to observe the exception.

Basically my code does this
```csharp
try {
    return await Simplifier.ReduceAsync(withSyntaxRoot);
} catch (Exception ex) {
    var warningText = "Conversion warning: Qualified name reduction failed for this file. " + ex;
    return doc.WithSyntaxRoot(WithWarningAnnotation(root, warningText));
}
```
And that catch block is never hit before the process dies.

I'll try to workaround the specific bug to avoid it simplifying nodes which will cause that exact error (there may be other similar ones), but I'll need some help from someone at Microsoft to deal with the general issue that Visual Studio exits with no chance to handle the error.

**Closed** 2020-01-11 12:31 UTC

**Comment by GrahamTheCoder** [comment] 2020-01-11 12:37
Todo: raise this issue on the roslyn repo

**Comment by GrahamTheCoder** [comment] 2020-02-21 16:40
Root cause: dotnet/roslyn#32785
