### ISSUE TITLE
"VB -> C#: " Conversion issue

### ISSUE THREAD

**Issue by kusabnis** [icsharpcode/CodeConverter#322] opened 2019-06-11 15:27 UTC
I have a VB project i am trying to convert to C#. When i convert it file by file the converter works as expected. But when i try to convert the whole solution in one go it changes the file extensions but does not create the file with converted contents in it. 

e.g. after conversion:

![image](https://user-images.githubusercontent.com/14319721/59285292-c0603380-8c3b-11e9-9ba7-f81ff9ecf2dc.png)

![image](https://user-images.githubusercontent.com/14319721/59285399-ed144b00-8c3b-11e9-8a17-80f17a1e926d.png)

**Comment by GrahamTheCoder** [comment] 2019-06-11 17:16
Hi, thanks for getting in touch. I believe this is a duplicate of #319 - files not under the solution directory are not converted (as a safety measure). I'll likely remove this check from the next release and replace it with a more robust check for overwriting files. Please add any other feedback to #319.

Thanks,
 Graham.

**Closed by GrahamTheCoder** 2019-06-11 17:16 UTC
