### ISSUE TITLE
Crash without notification.  Project too big?

### ISSUE THREAD

**Issue by derbkz** [icsharpcode/CodeConverter#521] opened 2020-02-10 10:01 UTC
### Steps to reproduce
If I want to convert my project, my Visual Studio always crashes, because my projects are very big. I have over 500 forms in some projects.

### Possible help
How about if you can choose a folder to convert the content. So you can work through the individual folders in the hope that the project will not crash? If you right click on a folder, you don't have the option to convert the content. Maybe you could add that?

### Error message shown
Visual Studio closes and has no feedback. When I start the program again, all are gone

### Details
* Product in use: e.g. [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: 7.6.0.0
* Microsoft Visual Studio Professional 2019 Version 16.4.4

**Comment by GrahamTheCoder** [comment] 2020-02-11 14:08
It may be possible to get that sort of crash due to sheer size, but I've seen this in the past caused by hitting a threading issue in the roslyn libraries. I worked around a similar issue in #484

You may be able to get Visual Studio to log the cause using the activity log (the stack trace would be really helpful):
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log
> Run Visual Studio with the /Log command line switch to write ActivityLog.xml to disk during your session.
> After closing Visual Studio, find the activity log in the subfolder for Visual Studio data:
> %AppData%\Microsoft\VisualStudio\<version>\ActivityLog.xml.

If that doesn't work, the next easiest way to get more debug information is run Visual Studio debugging another Visual Studio instance. I can talk you through that if we need to do so.

We'll track any progress on converting a folder in #485 - I certainly agree it'd be good for more purposes than just this

**Comment by GrahamTheCoder** [comment] 2020-02-15 16:45
I believe I have a fix for this for the imminent 7.8 release, but I'd still appreciate any extra information (or trying the latest master) to confirm.

**Closed** 2020-02-15 16:45 UTC

**Comment by GrahamTheCoder** [comment] 2020-02-21 16:40
Root cause: https://github.com/dotnet/roslyn/issues/32785
