### ISSUE TITLE
VB -> C#: expression NameOf results in "Cannot convert ClassBlockSyntax"

### ISSUE THREAD

**Issue by desbaratizador** [icsharpcode/CodeConverter#592] opened 2020-07-09 18:10 UTC
### Input code
<ApresentacaoColeccao(New String() {NameOf(Fornecedor.Codigo), NameOf(Fornecedor.Nome)}, 1)>
    Public Class Fornecedor
        Inherits ClasseDominio

        Public Overrides Function ToString() As String
            Return _nome
        End Function

        Protected _codigo As String
        Public Overridable Property Codigo As String
            Get
                Return _codigo
            End Get
            Set(value As String)
                _codigo = value
            End Set
        End Property
...

### Erroneous output
  /* Cannot convert ClassBlockSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.EmptyStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax'.
       at ICSharpCode.CodeConverter.CSharp.DeclarationNodeVisitor.<ConvertMemberAsync>d__45.MoveNext()

    Input:
        <Global.Logi.Dominio.Atributos.ApresentacaoColeccao(New String() {NameOf(Global.Logi.Dominio.Empresa.Fornecedor.Codigo), NameOf(Global.Logi.Dominio.Empresa.Fornecedor.Nome)}, 1)>
        Public Class Fornecedor
            Inherits Global.Logi.Dominio.ClasseDominio

            Public Overrides Function ToString() As String
                Return Me._nome
            End Function

            Protected _codigo As String
            Public Overridable Property Codigo As String
                Get
                    Return Me._codigo
                End Get
                Set(value As String)
                    Me._codigo = value
                End Set
            End Property

### Expected output
Trying to convert a full project and some classes failing to convert, the patterm is the use of the NameOf operator (when i replace the NameOf with a string constant the conversion goes well), this operator as all know has a direct counterpart in C#.

### Details
Using version 8.1.5.0 in Visual Studio.

**Comment by GrahamTheCoder** [comment] 2020-07-11 08:37
Hi, thanks for getting in touch. If I paste the input you gave into the [web converter](https://codeconverter.icsharpcode.net/) (which uses the same code) it converts fine - so I don't think it's NameOf causing the issue here. It mentions `MemberDeclarationSyntax`, so it's probably one of the class members that's been cut off when you pasted into Github, could you try again to paste the whole thing so I can investigate, thanks!

**Comment by desbaratizador** [comment] 2020-07-11 21:00
Hi,

First, thanks.

Tried also the web converter and the conversion was made, apparently exists some divergence between the two tools. Also i remember that when removed the NameOf expressions from the Fornecedor class, achieved a conversion without errors.  

See attached the Fornecedor and another VB .NET class and is failed C# conversions, in the new class NameOf seems to be also the problem.


Regards

Desbaratizador
[Failed_conversions.zip](https://github.com/icsharpcode/CodeConverter/files/4907594/Failed_conversions.zip)

**Comment by GrahamTheCoder** [comment] 2020-07-12 13:28
Thanks a lot. I'll check it in visual studio soon.

**Comment by GrahamTheCoder** [comment] 2020-07-12 21:48
I couldn't reproduce the issue, but looking at the code I can see the current behaviour could differ by Visual Studio version.
I've pushed a change to try to make it more consistent, which will be in the upcoming 8.1.6 release.
It'd be great if you could let me know you visual studio version (from the about box), and try out the new version when it's released.
Thanks!

**Comment by desbaratizador** [comment] 2020-07-13 22:30
Unfortunately the issue remains with version 8.1.6

**Comment by GrahamTheCoder** [comment] 2020-07-14 08:13
Thanks for checking, what visual studio version are you using?

**Comment by desbaratizador** [comment] 2020-07-15 20:37
Microsoft Visual Studio Community 2019 version 16.6.0

**Comment by GrahamTheCoder** [comment] 2020-07-21 22:15
Could you check if this cut down project works for you?
[Issue592And595ReproAttempt.zip](https://github.com/icsharpcode/CodeConverter/files/4943694/Issue592And595ReproAttempt.zip)


If it works fine, could you try to figure out what needs adding from your full project in order to break it (e.g. project type, target framework)?

**Comment by desbaratizador** [comment] 2020-07-22 00:30
It works fine (for both issues). But the NameOf problem occurs to me again and again, i'am trying to understand what's the difference...

**Comment by GrahamTheCoder** [comment] 2020-07-22 07:37
Thanks!

**Comment by GrahamTheCoder** [comment] 2020-07-22 07:42
The only time I've seen something like this is when the nuget packages weren't restored. I'm going to add something to the converter to warn people to (or automatically) do a full build if references can't be found.

**Comment by GrahamTheCoder** [comment] 2020-08-08 13:39
I've forced a build before conversion in the next release, so that might fix this. Reopen if you get a repro for 8.1.7+

**Closed by GrahamTheCoder** 2020-08-08 13:39 UTC
Labels: VB -> C#, needs-repro
