### ISSUE TITLE
VB -> C#: Extra type suffix

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#652] opened 2020-10-09 17:54 UTC
### Input code
```vbnet
    Public Shared Function Hypotenuse(ByVal polygon As IEnumerable(Of Double)) As Double
        If polygon Is Nothing Then Throw New ArgumentNullException(NameOf(polygon))
        Dim d As Double = 0
        For Each p As Double In polygon
            d += Math.Pow(p, 2D)
        Next
        d = Math.Sqrt(d)
        Return d
    End Function
```

### Erroneous output
```C#
        public static double Hypotenuse(IEnumerable<double> polygon)
        {
            if (polygon is null)
                throw new ArgumentNullException(nameof(polygon));
            double d = 0d;
            foreach (double p in polygon)
                d += Math.Pow(p, 2Dd);
            d = Math.Sqrt(d);
            return d;
        }
```

### Expected output
```C#
                d += Math.Pow(p, 2d);
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension
* Version in use: 8.1.8.0
* Visual Studio Community 2019 16.7.5
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment] 2020-10-10 22:25
Thanks, this was a recent regression. I'll close this since it is already tracked as https://github.com/icsharpcode/CodeConverter/issues/633

**Closed by GrahamTheCoder** 2020-10-10 22:25 UTC
Labels: VB -> C#
