### ISSUE TITLE
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0

### ISSUE THREAD

**Issue by eschneider999** [icsharpcode/CodeConverter#755] opened 2021-08-28 04:24 UTC
### Steps to reproduce
1.  Convert file to c#
2. 
3. 

### Error message shown
---------------------------
Code converter 8.3.0 - Visual Studio 15.9.28307.1622
---------------------------
An error has occured during conversion - press Ctrl+C to copy the details: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

   at ICSharpCode.CodeConverter.Shared.ProjectConversion.ConvertSingleAsync[TLanguageConversion](Document document, SingleConversionOptions conversionOptions, IProgress`1 progress, CancellationToken cancellationToken)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentUnhandledAsync>d__23`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass14_0`1.<<ConvertDocumentAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentAsync>d__14`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Support for VS2017 (15.*) is likely to end this year. You're using: 15.9.28307.1622
---------------------------
OK   
---------------------------

**Comment by GrahamTheCoder** [comment] 2021-08-28 08:36
Thanks for the report. I believe it's caused by an incompatible outdated extension/component (I've seen azure data lake tools cause this in #741)

4 days ago version 8.3.1 was released with code to try to work around this issue. Could you try updating to that?

**Comment by eschneider999** [comment] 2021-08-30 04:52
---------------------------
Code converter 8.3.1 - Visual Studio 15.9.28307.1622
---------------------------
An error has occurred during conversion - press Ctrl+C to copy the details: Assembly load issue detected. Tools->Options->Code Converter->BypassAssemblyLoadingErrors has now been automatically activated, please try again (but report this issue either way).

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

   at ICSharpCode.CodeConverter.Shared.ProjectConversion.ConvertSingleAsync[TLanguageConversion](Document document, SingleConversionOptions conversionOptions, IProgress`1 progress, CancellationToken cancellationToken)

   ...

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()

Support for VS2017 (15.*) is likely to end this year. You're using: 15.9.28307.1622

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].




---------------------------
OK   
---------------------------

**Comment by eschneider999** [comment] 2021-08-30 04:53
I download the source but it wants VS2019 and my solution is currently vs2017

**Comment by eschneider999** [comment] 2021-08-30 05:20
Tried to disable Azure Data lake got this:

---------------------------
Code converter 8.3.1 - Visual Studio 15.9.28307.1622
---------------------------
An error has occurred during conversion - press Ctrl+C to copy the details: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

   at ICSharpCode.CodeConverter.Shared.ProjectConversion.ConvertSingleAsync[TLanguageConversion](Document document, SingleConversionOptions conversionOptions, IProgress`1 progress, CancellationToken cancellationToken)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentUnhandledAsync>d__23`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<>c__DisplayClass14_0`1.<<ConvertDocumentAsync>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__78.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.CodeConversion.<ConvertDocumentAsync>d__14`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()



WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

   at ICSharpCode.CodeConverter.Shared.ProjectConversion.ConvertSingleAsync[TLanguageConversion](Document document, SingleConversionOptions conversionOptions, IProgress`1 progress, CancellationToken cancellationToken)

   ...

   at ICSharpCode.CodeConverter.VsExtension.ConvertVBToCSCommand.<ConvertDocumentAsync>d__24.MoveNext()

Support for VS2017 (15.*) is likely to end this year. You're using: 15.9.28307.1622

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].




---------------------------
OK   
---------------------------

**Comment by eschneider999** [comment] 2021-08-30 05:40
Updated Azure Data lake (still disabled) to 2.6.2000.0 and the Converter now works.

**Comment by GrahamTheCoder** [comment] 2021-09-06 07:11
I've made further tweaks to try to improve 2017 compatibility of the extension in the latest release so I'll close this issue.

The source code for the project however is only VS2019+
VS2019 Community edition is free and installs side by side with VS2017, so there's no reason for anyone to use an older version *for this solution* that I'm aware of.

**Closed** 2021-09-06 07:12 UTC
