### ISSUE TITLE
VB -> C#: Code not converted when there's a comment either side

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#637] opened 2020-10-05 15:16 UTC
### Input code
```vbnet
    Public Shared Function CountEntities(ByVal connection As System.Data.IDbConnection, ByVal partAutoId As Integer) As Integer
        Dim sqlBuilder As SqlBuilder = New SqlBuilder()
        ' #Disable Warning IDE0037 ' Use inferred member name
        Dim selector As SqlBuilder.Template = sqlBuilder.AddTemplate($"SELECT COUNT(*) FROM [{OhmniPartAttributeRangeBuilder.TableName}]
WHERE {NameOf(OhmniPartAttributeRangeNub.PartAutoId)} = @Id", New With {Key .Id = partAutoId})
        ' #Enable Warning IDE0037 ' Use inferred member name
        If selector.RawSql Is Nothing Then
            Throw New InvalidOperationException($"{NameOf(selector.RawSql)} null")
        ElseIf selector.Parameters Is Nothing Then
            Throw New InvalidOperationException($"{NameOf(selector.Parameters)} null")
        End If
        Return connection.ExecuteScalar(Of Integer)(selector.RawSql, selector.Parameters)
    End Function
```

### Erroneous output
```C#
        public static int CountEntities(System.Data.IDbConnection connection, int partAutoId)
        {
            // #pragma warning disable IDE0037 ' Use inferred member name
            var sqlBuilder = new SqlBuilder();
            ;
            // #pragma warning  restore IDE0037 ' Use inferred member name
            if (selector.RawSql is null)
            {
                throw new InvalidOperationException($"{nameof(selector.RawSql)} null");
            }
            else if (selector.Parameters is null)
            {
                throw new InvalidOperationException($"{nameof(selector.Parameters)} null");
            }

            return connection.ExecuteScalar<int>(selector.RawSql, selector.Parameters);
        }
```

### Expected output
```C#
        public static int CountEntities(System.Data.IDbConnection connection, string lotNumber)
        {
            var sqlBuilder = new SqlBuilder();
            var selector = sqlBuilder.AddTemplate(@$"select count(*) from [{CincoLotBuilder.TableName}] /**where**/");
            sqlBuilder.Where( $"{nameof( isr.Dapper.Ohmni.CincoLotNub.LotNumber)} = @lotNumber", new {lotNumber});
            if (selector.RawSql is null)
            {
                throw new InvalidOperationException($"{nameof(selector.RawSql)} null");
            }
            else if (selector.Parameters is null)
            {
                throw new InvalidOperationException($"{nameof(selector.Parameters)} null");
            }

            return connection.ExecuteScalar<int>(selector.RawSql, selector.Parameters);
        }

```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension / both
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix:
Removing the commented directive 
```
        ' #Disable Warning IDE0037 ' Use inferred member name
```
before retrying the conversion fixed this issue

**Comment by GrahamTheCoder** [comment] 2020-10-06 22:39
Hi there, thanks for the post. I'm having trouble reproducing the issue. When I paste it in https://codeconverter.icsharpcode.net/ the expected output comes out.
If it's happening within the Visual Studio extension only, there might be more of the surrounding context needed.
Thanks!

**Comment by AteCoder** [comment] 2020-10-06 22:54
Thank you for checking these!  Your work is much appreciated and, as I said in my review, this is the first time I am seeing a converter of such high quality.

Version 8.1.8.0
Installed 8/30/2020.

I can get you the source code files.  All of these reports are totally repeatable here on multiple files.  I am just going through a large project and these are all showing up on every file.

In fact, the source code is hosted on buitbucket

**Comment by GrahamTheCoder** [comment] 2020-10-28 16:50
Closing since I think #638 was the cause

**Closed by GrahamTheCoder** 2020-10-28 16:50 UTC
Labels: VB -> C#
