### ISSUE TITLE
C# -> VB: Return default converts to a string

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#493] opened 2020-01-13 10:09 UTC
### Input code
```csharp
class CSharpClass
{
	private static int GetNum()
	{
		System.Reflection.MethodInfo getDelegate = null;

		if (getDelegate == null)
		{
			return default;
		}

		return 1;
	}
}
```

### Erroneous output
```vbnet
Friend Class CSharpClass
    Private Shared Function GetNum() As Integer
        Dim getDelegate As MethodInfo = Nothing

        If getDelegate Is Nothing Then
            Return "default"
        End If

        Return 1
    End Function
End Class
```

### Expected output
```vbnet
Friend Class CSharpClass
	Private Shared Function GetNum() As Integer
		Dim getDelegate As System.Reflection.MethodInfo = Nothing

		If getDelegate Is Nothing Then
			Return 0
		End If

		Return 1
	End Function
End Class
```

### Details
Return default is being converted to Return "default".

* Version in use: Current compiled repository

**Comment by GrahamTheCoder** [comment] 2020-01-13 19:11
Duplicate of #428

**Closed** 2020-01-13 19:11 UTC
Labels: C# -> VB, duplicate
