### ISSUE TITLE
Exception on converting VB project to C#

### ISSUE THREAD

**Issue by panthernet** [icsharpcode/CodeConverter#554] opened 2020-04-01 19:03 UTC
### Steps to reproduce
1. Run VB > C# conversion on a very big project
2. Wait...
3. Get the error in a while

### Error message shown
![image](https://user-images.githubusercontent.com/5926603/78175927-f6d19e00-745b-11ea-8910-358edfa4af15.png)
```csharp
An error has occured during conversion: System.InvalidOperationException: No output available after posting output and waiting
at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.<>¢__DisplayClass1_02.< <ParallelSelectAwait> g__ReceiveAsync|0> d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions.<ParallelSelectAwait> d__1°2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Threading.Tasks.Sources. ManualResetValueTaskSourceCore 1,GetResult(Int16 token)
at ICSharpCode.CodeConverter.Shared.AsyncEnumerableTaskExtensions. <ParallelSelectAwait> d__1°2.System. Threading. Tasks.Sources.|ValueTaskSource< System.Boolean> .GetResult(Int16 token)
at System.Collections.Generic.AsyncEnumerableHelpers. <ToArrayWithLength> d__1°1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw),
at System.Collections.Generic.AsyncEnumerableHelpers. <ToArrayWithLength> d__1°1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at System. Threading.Tasks.ValueTask 1.get_Result(
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable 1.ConfiguredValueTaskAwaiter.GetResult()
at System.Collections.Generic. AsyncEnumerableHelpers.<ToArray> d__0'1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< Convert> d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Threading.Tasks.Sources. ManualResetValueTaskSourceCore 1,GetResult(Int16 token)
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< Convert> d__19.System.Threading.Tasks.Sources.IValueTaskSource< System.Boolean> .GetResult(Int16 token)
at System. Threading.Tasks.ValueTask 1.get_Result(
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< ConvertProjectContents > d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw),
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< ConvertProjectContents > d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Threading.Tasks.Sources. ManualResetValueTaskSourceCore 1,GetResult(Int16 token)
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< ConvertProjectContents > d__18.System.Threading.Tasks.Sources.|ValueTaskSource< System.Boolean> .GetResult(Int16 token)
at System. Threading.Tasks.ValueTask 1.get_Result(
at ICSharpCode.CodeConverter.Shared.ProjectConversion. < WithProjectFile> d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw),
at ICSharpCode.CodeConverter.Shared.ProjectConversion. < WithProjectFile> d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Threading.Tasks.Sources. ManualResetValueTaskSourceCore 1,GetResult(Int16 token)
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< WithProjectFile> d__13.System.Threading.Tasks.Sources.|ValueTaskSource< System.Boolean> .GetResult(Int16 token)
at System. Threading.Tasks.ValueTask 1.get_Result(
at ICSharpCode.CodeConverter.Shared.ProjectConversion. < ConvertProject> d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchinfo.Throw),
at ICSharpCode.CodeConverter.Shared.ProjectConversion. < ConvertProject> d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Threading.Tasks.Sources. ManualResetValueTaskSourceCore 1,GetResult(Int16 token)
at ICSharpCode.CodeConverter.Shared.ProjectConversion.< ConvertProject> d__12.System.Threading.Tasks.Sources.|ValueTaskSource< System.Boolean> .GetResult(Int16 token)
at System. Threading.Tasks.ValueTask 1.get_Result(
at System.Ling.AsyncEnumerable.SelectManyAsynciterator 2.<MoveNextCore> d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at System. Ling.AsynciteratorBase 1.< MoveNextAsync> d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Ling.AsynciteratorBase 1.< MoveNextAsync> d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at System.Ling.AsyncEnumerable.ConcatAsynciterator 1.<MoveNextCore> d__6,.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at System. Ling.AsynciteratorBase 1.< MoveNextAsync> d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System. Ling.AsynciteratorBase 1.< MoveNextAsync> d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.T hrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter. HandleNonSuccessAndDebuggerNotification(Task task)
at System. Threading.Tasks.ValueTask 1.get_Result(
at ICSharpCode.CodeConverter. VsExtension.CodeConversion.< ConvertProjectUnhandled> d__25'1.MoveNext()
```
### Details
* Product in use: VS extension
* Version in use: 8.0.4 on VS2019

**Comment by GrahamTheCoder** [comment] 2020-04-01 22:44
Hi, thanks for posting. I haven't seen this issue before and I'm particularly surprised to see it, and eager to get a fix. I'll have a look at the code tomorrow. Any extra context might help me track it down faster:
- Does anything appear on the code converter tab of the output window? 
- How long do you wait before it shows the error (since the last thing written in the output window)? 
- Is the cpu usage high while waiting? 
- How many logical cpus do you have? (Environment. ProcessorCount)
- If any file is mentioned in the output window, does converting just that file alone work?

**Comment by panthernet** [comment] 2020-04-02 06:38
Hi, let me know if I can provide additional info. I was counting on the converter to complete this project :(

- Happens consistently
- Happens on the exact project, others looks good
- Output window shows files one by one, nothing else
- I wait for several minutes until it fails (will check again)
- 30-40% of CPU
- 8 cpus
- Will check it asap

**Comment by panthernet** [comment] 2020-04-02 07:09
The project has 235 vb files many of which has 1000-3000 strings of code. Probably I can try to break it, but it is a real pain to do.

**Comment by GrahamTheCoder** [comment] 2020-04-02 11:11
I've managed to reproduce the issue locally in a unit test.
An error for one of the files in the process is causing the pipeline to stop accepting more items to convert. I'll try to get a fix, or at least a workaround available today in a CI build.

**Comment by GrahamTheCoder** [comment] 2020-04-02 13:14
I've tried to get more logging and exception information out, could you try the latest CI build by:
* Uninstalling the current code converter version
* Closing all Visual Studio windows and following the uninstall dialog
* Downloading the "1 published" artifact from [latest CI build](https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/latest?definitionId=2&branchName=master&status=succeeded)
* Running the vsix contained within that to install

Then re-attempt the conversion and let me know what the new exception is and as much detail as you can about which files say "started" but not "succeeded" in the output window for the converter.

i.e. If you can email them to me in a zip, great. If not: How many lines in the files, if you convert those files individually does it work, if you delete those files and try the conversion again does it succeed etc.

Thanks!

**Comment by panthernet** [comment] 2020-04-02 13:47
![image](https://user-images.githubusercontent.com/5926603/78255219-4e711780-74f7-11ea-9750-c4406bb69345.png)

Exception text just won't fit the screen.
I might have found the issue. Will send a PM.

**Comment by panthernet** [comment] 2020-04-02 13:50
Let me know how can I contact you privately, haven't seen PM on GitHub or any mails. Thanks!

**Comment by GrahamTheCoder** [comment] 2020-04-02 13:54
Thanks, feel free to email any private details to grahamthecoder@gmail.com

**Comment by panthernet** [comment] 2020-04-02 14:19
Yes! Conversion is complete now.

**Closed** 2020-04-02 14:26 UTC

**Comment by GrahamTheCoder** [comment] 2020-04-02 14:31
Great. The latest CI build should now support converting files with other vb extensions. Case closed. Thanks for debugging this with me!
