### ISSUE TITLE
VB -> C#: With on a structure type doesn't work after conversion-

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#661] opened 2020-10-22 10:47 UTC
Hello,

I have seen a problem with some with with when used with a structure type (Rectangle but probably point...).

### Input code
```vbnet
Public Class Form1
    Private rec As Rectangle
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        With rec
            .Height = 100
            .Y = 100
            .Width = 100
            .X = 100
        End With
        MessageBox.Show(rec.Height)
' Should show 100

    End Sub
End Class
```

### Erroneous output
```C#
public Form1()
        {
            InitializeComponent();
        }

        private Rectangle rec;

        private void Form1_Load(object sender, EventArgs e)
        {
            {
                var withBlock = rec;
                withBlock.Height = 100;
                withBlock.Y = 100;
                withBlock.Width = 100;
                withBlock.X = 100;
            }

            MessageBox.Show(rec.Height.ToString());
// Shows  0
        }
```-)

### Expected output
```C#
public Form1()
        {
            InitializeComponent();
        }

        private Rectangle rec;

        private void Form1_Load(object sender, EventArgs e)
        {
            {
                rec.Height = 100;
                rec.Y = 100;
                rec.Width = 100;
                rec.X = 100;
            }

            MessageBox.Show(rec.Height.ToString());
        }
```

### Details
Last plugin version.
When there is a struct type and a With, it is converted in a var Withblock but on a struct type you only change the copy of the structure not the original. (so changing the withBlock doesn't work.
The conversion is correct with a rectangle in the sub  but not when it is declared in the form (private)

* Version in use: 8.2.0.0
I guess it should be the same for point...

Marc

**Comment by GrahamTheCoder** [comment] 2020-10-23 08:01
Thanks, definitely worth some investigation. I'll close this as a duplicate of #634  and track progress there

**Closed by GrahamTheCoder** 2020-10-23 08:01 UTC
Labels: VB -> C#
