### ISSUE TITLE
VB -> C#: VS only: Global qualification / NameOf conversion issue

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#638] opened 2020-10-05 15:21 UTC
### Input code
```vbnet
    Private Shared Function CreateTable(ByVal connection As System.Data.SQLite.SQLiteConnection) As String
        Dim queryBuilder As New System.Text.StringBuilder
        queryBuilder.Append($"CREATE TABLE IF NOT EXISTS [{OhmniPartAttributeRangeBuilder.TableName}] (
[{NameOf(OhmniPartAttributeRangeNub.PartAutoId)}] integer NOT NULL, 
[{NameOf(OhmniPartAttributeRangeNub.AttributeTypeId)}] integer NOT NULL, 
[{NameOf(OhmniPartAttributeRangeNub.Min)}] float NOT NULL, 
[{NameOf(OhmniPartAttributeRangeNub.Max)}] float NOT NULL, 
CONSTRAINT [sqlite_autoindex_{OhmniPartAttributeRangeBuilder.TableName}_1] PRIMARY KEY ([{NameOf(OhmniPartAttributeRangeNub.PartAutoId)}], [{NameOf(OhmniPartAttributeRangeNub.AttributeTypeId)}]),
FOREIGN KEY ([{NameOf(OhmniPartAttributeRangeNub.PartAutoId)}]) REFERENCES [{CincoPartBuilder.TableName}] ([{NameOf(CincoPartNub.PartAutoId)}]) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ([{NameOf(OhmniPartAttributeRangeNub.AttributeTypeId)}]) REFERENCES [{OhmniPartAttributeRangeBuilder.AttributeTypeTableName}] ([{OhmniPartAttributeRangeBuilder.AttributeTypeForeignKeyName}]) ON UPDATE CASCADE ON DELETE CASCADE);
")
        connection.Execute(queryBuilder.ToString)
        Return OhmniPartAttributeRangeBuilder.TableName
    End Function

```

### Erroneous output
```C#
        private static string CreateTable(System.Data.SQLite.SQLiteConnection connection)
        {
            var queryBuilder = new System.Text.StringBuilder();
            ;
#error Cannot convert ExpressionStatementSyntax - see comment for details
            /* Cannot convert QualifiedNameSyntax, System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.NameSyntax'.
               at ICSharpCode.CodeConverter.CSharp.CommentConvertingVisitorWrapper.<ConvertHandledAsync>d__5`1.MoveNext()

            Input: Global.isr.Dapper
            Context:
                    queryBuilder.Append($"CREATE TABLE IF NOT EXISTS [{Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.TableName}] (
            [{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.PartAutoId)}] integer NOT NULL, 
            [{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.AttributeTypeId)}] integer NOT NULL, 
            [{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.Min)}] float NOT NULL, 
            [{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.Max)}] float NOT NULL, 
            CONSTRAINT [sqlite_autoindex_{Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.TableName}_1] PRIMARY KEY ([{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.PartAutoId)}], [{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.AttributeTypeId)}]),
            FOREIGN KEY ([{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.PartAutoId)}]) REFERENCES [{Global.isr.Dapper.Ohmni.CincoPartBuilder.TableName}] ([{NameOf(Global.isr.Dapper.Ohmni.CincoPartNub.PartAutoId)}]) ON UPDATE CASCADE ON DELETE CASCADE,
            FOREIGN KEY ([{NameOf(Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeNub.AttributeTypeId)}]) REFERENCES [{Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.AttributeTypeTableName}] ([{Global.isr.Dapper.Ohmni.OhmniPartAttributeRangeBuilder.AttributeTypeForeignKeyName}]) ON UPDATE CASCADE ON DELETE CASCADE);
            ")

             */
            connection.Execute(queryBuilder.ToString());
            return TableName;
        }

```

### Expected output
```C#
        private static string CreateTable(System.Data.SQLite.SQLiteConnection connection)
        {
            var queryBuilder = new System.Text.StringBuilder();
            queryBuilder.Append(@$"CREATE TABLE IF NOT EXISTS [{isr.Dapper.Ohmni.CincoLotBuilder.TableName}] (
                [{nameof( isr.Dapper.Ohmni.CincoLotNub.LotAutoId)}] integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
                [{nameof( isr.Dapper.Ohmni.CincoLotNub.PartAutoId)}] integer NOT NULL, 
                [{nameof( isr.Dapper.Ohmni.CincoLotNub.LotNumber)}] nvarchar(50) NOT NULL, 
                [{nameof( isr.Dapper.Ohmni.CincoLotNub.PartNumber)}] nvarchar(50) NOT NULL, 
                [{nameof( isr.Dapper.Ohmni.CincoLotNub.Timestamp)}] datetime NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
            FOREIGN KEY ([{nameof( isr.Dapper.Ohmni.CincoLotNub.PartAutoId)}]) REFERENCES [{isr.Dapper.Ohmni.CincoPartBuilder.TableName}] ([{nameof( isr.Dapper.Ohmni.CincoLotNub.PartAutoId)}]) ON UPDATE CASCADE ON DELETE CASCADE); 
            CREATE UNIQUE INDEX IF NOT EXISTS [UQ_{isr.Dapper.Ohmni.CincoLotBuilder.TableName}] ON [{isr.Dapper.Ohmni.CincoLotBuilder.TableName}] ([{nameof( isr.Dapper.Ohmni.CincoLotNub.LotNumber)}]); ");
            connection.Execute(queryBuilder.ToString();
            return TableName;
        }

```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) VS extension 
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment] 2020-10-06 22:46
Thanks for posting, I'm afraid I can't reproduce any of your issues on https://codeconverter.icsharpcode.net/
Can you provide more info on which version of which converter you're using?

**Comment by AteCoder** [comment] 2020-10-06 23:03
Microsoft Visual Studio Community 2019
Version 16.7.5

Attached are a few files showing the issues I have been reporting.
[Entities.zip](https://github.com/icsharpcode/CodeConverter/files/5337331/Entities.zip)

**Comment by GrahamTheCoder** [comment] 2020-10-06 23:04
Ah, great, thanks!

**Comment by GrahamTheCoder** [comment] 2020-10-06 23:10
Could also be related to https://github.com/icsharpcode/CodeConverter/issues/592 though I never figured out the cause of that

**Comment by AteCoder** [comment] 2020-10-06 23:15
Maybe the issue is with the Global namespace prefix:

Maybe  nameof( global::

**Comment by GrahamTheCoder** [comment] 2020-10-11 22:28
I can confirm that if I stick a project file in with those 4 files then there are no conversion errors. I specifically checked the bits of code for this, #639 and #640 and all looked to be converted sensibly.

It's worth noting that I wasn't starting from a compiling solution - though I did make an effort by installing things like: Dapper, Dapper.contrib, Dapper.SqlBuilder, System.ComponentModel.Annotations, System.Data.SQLite, UmbracoCms, UmbracoCms.Core to try to satisfy some of the dependencies.

It seems like what's happening, is that for compiling solutions, the (pre-conversion) expansion phase qualifies some namespaces as global, then the conversion converts it as a member access expression rather than a qualified name.
I've removed some code that outputs member access expressions that I'd previously added to workaround a compiler issue - I suspect the issue has been fixed in the version of VS you're using, and the problem it caused in other versions was less severe.

If you could try out a source/CI build to test the fix that'd be great (see readme file or ask for more info if needed)

**Comment by AteCoder** [comment] 2020-10-11 22:46
Will do.  I am preparing another large solution for conversion, that would likely pose new challenges.  I will connect with you before going forward with the conversion to figure out how to test these fixes.
________________________________

**Comment by AteCoder** [comment] 2020-10-12 04:34
it looks like the source code requires the .Net Core SDK which I have not installed on my system.  Can I get get a pre-release VSIX?

**Comment by GrahamTheCoder** [comment] 2020-10-12 15:37
You may be able to compile and run the extension without the .net core sdk present (ignore the non-loading projects).
But it's probably easier to just remove the current installed extension and install a CI build such as this one: https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=1749&view=artifacts&type=publishedArtifacts

**Comment by AteCoder** [comment] 2020-10-12 16:09
Got it.
Was there a way that I could get this artifact from the pipelines page?

**Comment by AteCoder** [comment] 2020-10-28 16:23
it looks like the 8.1.8.0 artifact of 10/12 fixed this issue.

**Comment by GrahamTheCoder** [comment] 2020-10-28 16:48
That's great, thanks for confirming!

**Closed by GrahamTheCoder** 2020-10-28 16:48 UTC
Labels: VB -> C#
