### ISSUE TITLE
VB -> C#: Erroneous new keyword

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#431] opened 2019-11-19 11:12 UTC
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vbnet
Class Base
    Public Sub Add(ByVal key As String, ByVal obj As Object)
    End Sub
End Class

Class Derived
    Inherits Base

    Public Overloads Sub Add(ByRef obj As Object)

    End Sub
End Class
```

### Erroneous output
```c#
class Base
{
    public void Add(string key, object obj)
    {
    }
}

class Derived : Base
{
    public new void Add(ref object obj)
    {
    }
}
```

### Expected output
```c#
class Base
{
    public void Add(string key, object obj)
    {
    }
}

class Derived : Base
{
    public void Add(ref object obj)
    {
    }
}
```

### Details

* Version in use: 7.2.0

Warning:
```
warning CS0109: The member 'Derived.Add(ref object)' does not hide an accessible member. The new keyword is not required.
```

**Comment by GrahamTheCoder** [comment] 2019-11-19 19:42
Similar: https://github.com/icsharpcode/CodeConverter/issues/351

**Comment by GrahamTheCoder** [comment] 2020-03-09 00:11
Duplicate of #504 - see that for details of the recent fix

**Closed by GrahamTheCoder** 2020-03-09 00:11 UTC
Labels: VB -> C#
