### ISSUE TITLE
VB -> C#: function argument is placed within brackets

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#648] opened 2020-10-07 00:52 UTC
### Input code
```vbnet
    Public Sub UpdateTimestamp(ByVal connection As System.Data.IDbConnection, ByVal key As Integer, ByVal universalTimestamp As Date)
        If connection Is Nothing Then Throw New ArgumentNullException(NameOf(connection))
        Dim queryBuilder As New System.Text.StringBuilder
        queryBuilder.Append($"UPDATE [{Me.TableNameThis}] ")
        queryBuilder.Append($"SET [{NameOf(KeyLabelTimezoneNub.Timestamp)}] = '{Me.ToTimestampFormat(universalTimestamp)}' ")
        queryBuilder.Append($"WHERE [{NameOf(KeyLabelTimezoneNub.AutoId)}] = {key}; ")
        connection.Execute(queryBuilder.ToString().Clean())
    End Sub
```

### Erroneous output
```C#
        public void UpdateTimestamp(System.Data.IDbConnection connection, int key, DateTime universalTimestamp)
        {
            if (connection is null)
                throw new ArgumentNullException(nameof(connection));
            var queryBuilder = new System.Text.StringBuilder();
            queryBuilder.Append($"UPDATE [{TableNameThis}] ");
            queryBuilder.Append($"SET [{nameof( KeyLabelTimezoneNub.Timestamp)}] = '{this.ToTimestampFormat(universalTimestamp)}' ");
            queryBuilder.Append($"WHERE [{nameof( KeyLabelTimezoneNub.AutoId)}] = {[key]}; ");
            connection.Execute(queryBuilder.ToString().Clean());
        }
```

### Expected output
```C#
        public void UpdateTimestamp(System.Data.IDbConnection connection, int key, DateTime universalTimestamp)
        {
            if (connection is null)
                throw new ArgumentNullException(nameof(connection));
            var queryBuilder = new System.Text.StringBuilder();
            queryBuilder.Append($"UPDATE [{TableNameThis}] ");
            queryBuilder.Append($"SET [{nameof( KeyLabelTimezoneNub.Timestamp)}] = '{this.ToTimestampFormat(universalTimestamp)}' ");
            queryBuilder.Append($"WHERE [{nameof( KeyLabelTimezoneNub.AutoId)}] = {key}; ");
            connection.Execute(queryBuilder.ToString().Clean());
        }

```

### Details
* Product in use:  [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* VS Community 16.7.5
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment] 2020-10-09 00:54
At a glance it looks like what's happened, is before conversion, key was escaped due to being a keyword, and afterwards, didn't get the escaping removed. I think it should be an easy fix somewhere near ConvertIdentifier

**Comment by GrahamTheCoder** [comment] 2020-10-12 15:04
Similarly to the csTab issue, I can't reproduce this when converting just that snippet. I created a minimal compilable standalone file from it, and it still doesn't reproduce the issue:

```vbnet
Imports System

Public Class X
    Dim TableNameThis As String = ""
   Public Sub UpdateTimestamp(ByVal connection As System.Data.IDbConnection, ByVal key As Integer, ByVal universalTimestamp As Date)
        If connection Is Nothing Then Throw New ArgumentNullException(NameOf(connection))
        Dim queryBuilder As New System.Text.StringBuilder
        queryBuilder.Append($"UPDATE [{Me.TableNameThis}] ")
        queryBuilder.Append($"SET [{NameOf(KeyLabelTimezoneNub.Timestamp)}] = '{Me.ToTimestampFormat(universalTimestamp)}' ")
        queryBuilder.Append($"WHERE [{NameOf(KeyLabelTimezoneNub.AutoId)}] = {key}; ")
    End Sub

    Private Function ToTimestampFormat(universalTimestamp As Date) As Object
        Throw New NotImplementedException()
    End Function
End Class
    
Public Class KeyLabelTimezoneNub
        Public Timestamp As DateTime
        Public AutoId As Integer
End Class
```

I notice there are other oddities too, like a space character after "nameof(" in the conversion - are you running the input/output through any other program (or for example doing some manually find/replaces) as part of the conversion that could be causing these different results?

**Comment by AteCoder** [comment] 2020-10-12 15:25
Yep, as I said on the .vbTab issue, by the time I get the report to you, the error report might have changed making it hard to reproduce the issue.  Obviously, I naively thought such issues could be isolated to the immediate code snippet. Now I understand that, like in spoken language, context matters.

Specifically, before the conversion, I comment out directives such as #region and #end region and change #End Region to ‘ #endregion.  I also commented out #diable/#enable. After the conversion I restore the directives, try to fix code alignment issues (e.g., first row /// <summary> gets indented differently from other rows) and, now also, fix known issues (and that’s where the space was added to ‘nameof(‘.)

I was thinking that I might be able to keep the VB code intact for reproducing these issues but now am wondering if this might be for naught seeing that context would be hard to preserve.

Clearly, your challenge in creating a quality converter is formidable.  You have done a great job!

I’ll continue reporting the issues and try to give you as much info as I can.  I have the code in open repositories but trying to restore the code to the pre-conversion state and reproduce this issue will likely be quite tasking.

**Comment by GrahamTheCoder** [comment] 2020-10-12 16:06
Ah yes, sorry I hadn't seen that other message yet, that's a great help to know though!
There are some suggestions for how to go through a big conversion process here: https://github.com/icsharpcode/CodeConverter/wiki

The ideal for each issue is to try to find the minimal, compilable unit of code that displays the issue - since that's what I'll put in the tests to avoid regressions.

**Comment by AteCoder** [comment] 2020-10-12 16:22
I do not commit after the conversion is done. My thinking was that this is committing a messy code.  What I can do, though, is backup the copy of the solution before and after the conversion.

On the conversion, here is a short list of what I do to prepare for the conversion from VB to C#:


  *   Remove the Settings auto save functionality in class libraries;
  *   Change parametrized properties to Getters and Setters;
  *   Remove all 'With' clauses (Lookup 'End With');
  *   Change Static variables to class private fields;
  *   Review #If directives for inclusion or comment out;
  *   Test;
  *   Commit;
  *   Update code documentation (I am using Atomineer, which creates it’s own issues);
  *   Commit;
  *   Comment out directives such as #Region, #Dispable; #Enable.

**Comment by GrahamTheCoder** [comment] 2020-10-12 16:59
Yeah it's a big continuum really and it depends on the repo/environment (e.g. how may readers/writers of the repo). Some people will leave in every single typo and have a separate commit to fix it, whereas since I'm very familiar with git commands and tend to rewrite the commit since there's no value to anyone seeing it again. If there's a big automated change though (e.g. regex replace) I always try to keep it separate from surrounding changes so that I can see where things went wrong more clearly - what else is history for? One of the nice things about git is that you can work on your branch with lots of commits making it easy to spot and fix mistakes, then easily squash all those commits down when you're done.

Anyway, everyone's got to do what's right for them, thanks for the list!

**Comment by AteCoder** [comment] 2020-10-12 17:12
Would you mind sharing with me a set of git commands I could you before and after converting a project to allow me to share more info with you?

I presume this would include:

  *   Branch into the conversion branch
  *   Convert
  *   Commit
  *   Fix the code and report issues;
  *   Commit
  *   Cleanup code: fix comments etc.
  *   Commit
  *   Merge the code into master (not politically correct);
  *   …. let open conversion issues close;
  *   Remove the conversion branch

I use both Git Extensions and Tortoise Git. But am thinking this would be a good case for running naked GIT commends to make sure things are done right.

**Comment by AteCoder** [comment] 2020-10-13 00:34
Got it branching working on a test repo.  Magic.

From: David Hary<mailto:david.hary@outlook.com>
Sent: Monday, October 12, 2020 10:12 AM
To: icsharpcode/CodeConverter<mailto:reply@reply.github.com>; icsharpcode/CodeConverter<mailto:CodeConverter@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [icsharpcode/CodeConverter] VB -> C#: function argument is placed within brackets (#648)

Would you mind sharing with me a set of git commands I could you before and after converting a project to allow me to share more info with you?

I presume this would include:

  *   Branch into the conversion branch
  *   Convert
  *   Commit
  *   Fix the code and report issues;
  *   Commit
  *   Cleanup code: fix comments etc.
  *   Commit
  *   Merge the code into master (not politically correct);
  *   …. let open conversion issues close;
  *   Remove the conversion branch

I use both Git Extensions and Tortoise Git. But am thinking this would be a good case for running naked GIT commends to make sure things are done right.

**Comment by GrahamTheCoder** [comment] 2020-10-13 08:38
Great, yes that sounds like the right sequence of steps. If you find an issue later down the line, look at the file history of the output file and put the contents from immediately after the conversion into the issue to give the best chance of tracking down the problem

I'm a big fan of git extensions since each action maps directly to a single git command, but makes it much easier to see what's going on.

When you want to merge just:
git checkout master
git merge yourconversionbranch
See here for some worked examples:
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by AteCoder** [comment] 2020-10-14 17:41
...on that note, 

C# Nothing == Nothing is True whereas it is Nothing in VB

C# Flags Enum with a zero None element prepends 'None, ' on the ToString() value. VB ignores the zero value. So, contrary to the code analysis old rules, Flags Enum should not include a None '0' value.

**Comment by GrahamTheCoder** [comment] 2020-10-28 17:09
Here's a [VB example program](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfACgVwsAlgYwAQGFgBDAZxNwA8BYAKF3t1odzQx1wGUALIgJwFMYndLgCyRTADsAFAEomzBgBFMAW0q4AguQDyEAFb9sAF1wBeXADkA9sa5SA5uau37khwsWcAniWP9VADp8a0kSa2B+QIB1Xkx/ABkpfmkKeToGAFFJIQ50WmyhQlISIA===) showing that Nothing = Nothing

Here's some [VB](https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwAqImAEsBjAAgGFgBDAZ1rIEEq7aBYAKDO7P0NLIBlABbV4AUzRCCZALLUiyABQBKTjw1kAIkQC2ZAHIB7ZOMbI0AeVNkAvGQBCisQE8AdMZuX4j5/HfW4uqa3Dr6geZoACoA7kZ2vsiuboFk3onJsUbBIYIutDDium4UJrRGwOJuAOrwRIUAMoriSp5mFoFuUUaCMHXIAOaqalwhQvmFxaXI5ZU1dY3NShEWWV09fYpDKiMaAKIW0hCcB1Is9JycADx5BUVuAGI0A7QAfJx8xOQHiPpOSf4coYTEFRtxAkCsidDj9dEA=) and [converted C#](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AEQEsBDAcygHsBnYKgY2YG49CTyASgFMAZgBsh7Noyg98xUmQHQ2AWyFkAwo1UAHKhLABlIWABuHIdzx4A2jWbMhqgEZiAniCLa9BmtKhhMRoAD38qGWYACgAOAEoAXTsHJ1cPL2UoNSEfXXCXAypgdyiAdTAaXQA5GQBREPYhXQCAFQALMEYAd2YiAF4iYEghROTHZzdPIgohFwg6Oho3ISiZuYWliQBBYCGqOeANNfm6Kig6AFlGOCtKURoIMWAiZGnZk82hHb2Do/eFs6Xa63ajMT4AeWaVFUVAAXuFIi83utFstvmB9hBDncUYCrjdmGQAJIMRhgIRGdyuRhiIzAMkUoQARwgQigjQACowzsBeq9jhs0bsMb8cSc8cDCbUoJ9anAilsoHBtFkzqzRrh7OM0lMttrJgA1UzMCJQKIAIgIZCtNvNGtQAGYSOgiFtNMFHHgAN54Ih+53oX3+n24f1hogAITONDA7iIBRlsf6kejsbINSgQiRUcT7jI4MzcnD/pzMbjCbLLoGpbTBazrxreZaXUYReL/AAnFEK2mWow6RjzlE4nE28XSF2e+50GQ+wPAcPR0G/QBfPBrzUAMWCdGYSXwTrZEFUKdz3uXRAzWYGBBCBBgF7rydvmAfof9zcYz5CgdwG6AA) showing that enums don't include the none flag when ToString is called (it's a .NET method so it doesn't differ between C# and VB).

The above are counterexamples to the behaviour described, but obviously there may be some compilation options which change equality behaviour, or make enums start with the first element being equal to 1, that could cause the effect you've described. I'll close this issue since it was tracking something with a root cause in #638, but please open a new issue referencing this comment if you pin down a specific code snippet showing the issue. Thanks!

**Closed by GrahamTheCoder** 2020-10-28 17:09 UTC
Labels: VB -> C#, compilation error, needs-repro

**Comment by AteCoder** [comment] 2020-10-28 17:20
The behavior I have seen is with a generic function passing an Enum as the generic type.  I will try to put together an example.

**Comment by GrahamTheCoder** [comment] 2020-10-28 17:53
If you compare a value-type Nothing to reference type Nothing they may differ using the = operator
Something like [this](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfACgVwsAlgYwAQGFgBDAZxNwEFDSSBYAKFydwedzQx1wGUALIgE4BTGD3S4AskUwA7ABQBKVm2YARTAFtcAD0rkAkjIAuQgOZCBuALy4AcgHsjvWaeUrc6rQE89uAPIQAFZC2EbWdo7OMq6M7h6auABevgHBoeG6Nl5uKtxeJCYaAHT49jIk9sBCRQDqApgmADKyQnKJSrFMAKIyotzoDD2i1GRAA) perhaps. I haven't tried out running that since it's not allowed to run on that website.

**Comment by AteCoder** [comment] 2020-10-28 19:02
These are the equivalent assertion in VB and C# to which I was referring:
VB: Assert.**IsNull**(New Boolean? = New Boolean?, "? Null = New Boolean? = New Boolean?")
C#: Assert.**IsNotNull**( new bool?() == new bool?(), "? Null = new bool?() = new bool?()" );

I believe C# and VB use different standard on Nullable comparisons, by design. 

I am unable to reproduce the Enum ToString() issue now.  It came up in code that failed after the conversion to C# when called from a VB program.  I was getting the Enum Description from the Enum value. The derivation of the description failed because ToString() returned a composite of the name and None.  So I changed the code to use Enum.GetName().  I will try to trace later on and see if I can provide an example.
