### ISSUE TITLE
VB -> C#: VB comment left unchanged within a function

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#647] opened 2020-10-06 23:22 UTC
### Input code
```vbnet
    Public Shared Function CountEntities(ByVal connection As System.Data.IDbConnection, ByVal label As String) As Integer
        Dim sqlBuilder As SqlBuilder = New SqlBuilder()
        ' Dim selector As SqlBuilder.Template = builder.AddTemplate($"SELECT COUNT(*) FROM [{ElementTypeNub.TableName}] 
        ' WHERE {NameOf(ElementTypeNub.PlatformName)} = @PlatformName", New With {Key .PlatformName = PlatformName})
        Dim selector As SqlBuilder.Template = sqlBuilder.AddTemplate(
            $"SELECT COUNT(*) FROM [{ElementTypeBuilder.TableName}] WHERE {NameOf(ElementTypeNub.Label)} = @label", New With {label})
        If selector.RawSql Is Nothing Then
            Throw New InvalidOperationException($"{NameOf(selector.RawSql)} null")
        ElseIf selector.Parameters Is Nothing Then
            Throw New InvalidOperationException($"{NameOf(selector.Parameters)} null")
        End If
        Return connection.ExecuteScalar(Of Integer)(selector.RawSql, selector.Parameters)
    End Function

```

### Erroneous output
```C#
        public static int CountEntities(System.Data.IDbConnection connection, string label)
        {
            // Dim selector As SqlBuilder.Template = builder.AddTemplate($"SELECT COUNT(*) FROM [{ElementTypeNub.TableName}] 
            // WHERE {NameOf(ElementTypeNub.PlatformName)} = @PlatformName", new {PlatformName = PlatformName})
            var sqlBuilder = new SqlBuilder();
            ' Dim selector As SqlBuilder.Template = builder.AddTemplate($"SELECT COUNT(*) FROM [{ElementTypeNub.TableName}] 
                    ' WHERE {NameOf(ElementTypeNub.PlatformName)} = @PlatformName", new {PlatformName = PlatformName})
                    SqlBuilder.Template selector = sqlBuilder.AddTemplate(
                        $"SELECT COUNT(*) FROM [{isr.Dapper.Entities.ElementTypeBuilder.TableName}] WHERE {nameof( ElementTypeNub.Label)} = @label", new {label});
            if (selector.RawSql is null)
            {
                throw new InvalidOperationException($"{nameof(selector.RawSql)} null");
            }
            else if (selector.Parameters is null)
            {
                throw new InvalidOperationException($"{nameof(selector.Parameters)} null");
            }

            return connection.ExecuteScalar<int>(selector.RawSql, selector.Parameters);
        }
```

### Expected output
```C#
        public static int CountEntities(System.Data.IDbConnection connection, string label)
        {
            // Dim selector As SqlBuilder.Template = builder.AddTemplate($"SELECT COUNT(*) FROM [{ElementTypeNub.TableName}] 
            // WHERE {NameOf(ElementTypeNub.PlatformName)} = @PlatformName", new {PlatformName = PlatformName})
            var sqlBuilder = new SqlBuilder();
            SqlBuilder.Template selector = sqlBuilder.AddTemplate(
                        $"SELECT COUNT(*) FROM [{isr.Dapper.Entities.ElementTypeBuilder.TableName}] WHERE {nameof( ElementTypeNub.Label)} = @label", new {label});
            if (selector.RawSql is null)
            {
                throw new InvalidOperationException($"{nameof(selector.RawSql)} null");
            }
            else if (selector.Parameters is null)
            {
                throw new InvalidOperationException($"{nameof(selector.Parameters)} null");
            }

            return connection.ExecuteScalar<int>(selector.RawSql, selector.Parameters);
        }
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)  
* VS 2019 16.7.4 community
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? N/a
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment] 2020-10-12 15:40
I couldn't reproduce this. However, in the files you provided me, the CountEntities conversion came out differently - in a way that I can reproduce something close to. The root cause was https://github.com/icsharpcode/CodeConverter/issues/638. Though it seems that the error details got lost, so I'll have a look if that can be improved as part of this issue

**Comment by GrahamTheCoder** [comment] 2020-10-28 16:49
Closing since I think #638 was the cause and have tried to improve the error details given too

**Closed by GrahamTheCoder** 2020-10-28 16:49 UTC
Labels: VB -> C#
