### ISSUE TITLE
StackOverflowException crashes Visual Studio on deeply nested expression

### ISSUE THREAD

**Issue by filippobarbuscatec** [icsharpcode/CodeConverter#1033] opened 2023-09-14 10:32 UTC
Hi,
we have some problems converting a .NET Core 6 project written in VB.NET into C#.
We have a solution with various projects. The tool works flawlessly on medium-sized projects and single files.
On larger projects, after a few minutes Visual Studio restarts without giving any error messages.
We noticed that the visual studio process uses up 100% of the CPU for the minutes it works and takes up all the available RAM.
In the event log there is the following error:
```
Application name generating the error: devenv.exe, version: 17.7.34024.191, timestamp: 0x64e7d3da
Form name generating the error: Microsoft.CodeAnalysis.VisualBasic.ni.dll, version: 4.700.23.41608, timestamp: 0xbc31604d
Error code: 0xc00000fd
Offset error 0x0000000000a2ab8f
Process ID generating the error: 0x0xB438
Launch time of the application generating the error: 0x0x1D9E62070FDCA25
Path to the application generating the error: C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe
Path to the form that generated the error: C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.Cf3d5ce20#\1a4d62a8a75088940c54a1deb5d4e1e0\Microsoft.CodeAnalysis.VisualBasic.ni.dll
Report ID: 4a9825c0-e276-459d-91a5-ec33e668f4ec
Full packet name generating the error:
Application ID related to the packet generating the error:
```
### Details
* The extension we are using is version 9.2.3.0
* The Visual Studio version is the 2022, to be precise, 17.7.3
* The project framework is .NET Core 6

**Comment by GrahamTheCoder** [comment] 2023-09-16 21:08
Thanks for the report. It may be possible to make a more incremental process to solve this. I've forgotten what stopped me doing that previously but will take a look

**Comment by filippobarbuscatec** [comment] 2023-09-20 07:20
HI
Here is the data of the project on which we are testing the extension:
- Source code lines: 103,410
- Files with code: 249
- Classes: 401

In this project there are files with over 6000 lines of code
Consider that among the projects I have to convert this is not the largest and I have projects with Forms where the Designer file is quite large.

What can I do to help you debug the problem?
Is there any LOG I can pass on to you?
Thank you

**Comment by GrahamTheCoder** [comment] 2023-09-20 08:38
Ah ok, so the problem is likely the size of individual files rather than total project/solution size. So I think it's the same as https://github.com/icsharpcode/CodeConverter/issues/877 which has some suggestions like splitting big files into partial classes. Tweaking the options around formatting and timeouts also may help.
I'll try again to reproduce this today. Obviously if you can provide the project to me privately that would be a huge help, the other thing you can do is create a project containing just the single biggest file, and seeing if that converts successfully. And finally you can run another instance of the code converter to debug and see where the converter crashes. Last time I looked I think it was in roslyns formatting, but would be good to confirm.

**Comment by filippobarbuscatec** [comment] 2023-09-20 14:02
HI
I cannot provide the project because it is the property of the company where I work.
I did a test in a project with only the largest file and it worked.
I tried running the command line tool and the error it gives is:
```
Phase 1 of 2:

* eWorking\eW.eWorking.DataLayer\Documenti\DocumentiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Anagrafica\NucleiFamiliariComponentiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Anagrafica\NucleiFamiliariDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Modelli\ModelliDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Pratica\PraticaDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Procedimenti\ProgettoDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Procedimenti\FasiProcedimentoDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Organigramma\FunzioniAssegnazioni\FunzioneAssegnazioneModDocumentiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Organigramma\FunzioniAssegnazioni\FunzioneAssegnazioneModDocumentiDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Procedimenti\ProgettoDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Organigramma\AddettiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Documenti\DocumentiPassaggiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Anagrafica\NucleiFamiliariDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Appalti\ContrattoDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Modelli\ModelliDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Documenti\DocumentiAllegatiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Anagrafica\NucleiFamiliariComponentiDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Zoom\ZoomDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\eWorkingServer\ModelliPCASADataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Appalti\ContrattoDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Organigramma\AddettiDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\FatturaPA\FatturaPassivaDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Documenti\DocumentiAllegatiDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Documenti\TipoDocumentoDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\eWorkingServer\ModelliPCASADataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Anagrafica\AnagrafeTributariaDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\FatturaPA\FatturaPassivaDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Procedimenti\ProcedimentoDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Zoom\ZoomDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\MessaggiDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Procedimenti\FasiProcedimentoDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\SistemaGestionale\MenuOpzioneDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\MessaggiDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\ExportXml\ExportXmlDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Anagrafica\AnagrafeTributariaDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\RegistroOperatore\RegistroOperatoreDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\SistemaGestionale\MenuOpzioneDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Query\QueryDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\Procedimenti\ProcedimentoDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\Pratica\FasiPraticaDataMapper.vb - conversion started

* eWorking\eW.eWorking.DataLayer\ExportXml\ExportXmlDataMapper.vb - conversion succeeded

* eWorking\eW.eWorking.DataLayer\eWorkingServer\CalcoloResiduiServiceDataMapper.vb - conversion started

Process is terminated due to StackOverflowException.
```
To do the last check you were asking about, how do I run another instance of the code converter for debugging?

**Comment by GrahamTheCoder** [comment] 2023-09-20 17:19
Thanks, interesting that it's a stackoverflow and in phase 1. That sounds like a different issue to the one I linked to. Getting the stack trace will be very useful there. To debug the code converter, either run it from source, or just start an instance of visual studio, and click something like debug, attach, then select devenv.exe for the instance where you are about to attempt the conversion. By default it should break when the stackoverflow exception happens and then you can look at the stack trace and copy paste it.
Knowing exactly which file it's working on May help narrow things down. It does several in parallel so may not be the last listed in the log you posted. Thanks for your help!

**Comment by filippobarbuscatec** [comment] 2023-09-22 08:56
HI
I debugged the problem and identified which files were causing the problem.
In both cases there was a very long concatenated string variable for example:

`dim str as string = "row 1" & vbCrLf &
"row 2" & vbCrLf &
"row 3" & vbCrLf &
"row 4" & vbCrLf &
"row 5" & vbCrLf &
"row 6" & vbCrLf &
"row 7" & vbCrLf &
"row 8" & vbCrLf &
"row 9" & vbCrLf &
"row 10" & vbCrLf &
"row 11" & vbCrLf &
"row 12" & vbCrLf &
"row 13" & vbCrLf &
"row 14" & vbCrLf &
"row 15" & vbCrLf &
"row 16" & vbCrLf &
"row 17" & vbCrLf &
"row 18" & vbCrLf &
"row 19" & vbCrLf &
"row 20" & vbCrLf &
"row 21" & vbCrLf &
"row 22" & vbCrLf &
"row 23" & vbCrLf &
"row 24" & vbCrLf &
"row 25" & vbCrLf &
"row 26" & vbCrLf &
"row 27" & vbCrLf &
"row 28" & vbCrLf &
"row 29" & vbCrLf &
"row 30" & vbCrLf &
"row 31" & vbCrLf &
"row 32" & vbCrLf &
"row 33" & vbCrLf &
"row 34" & vbCrLf &
"row 35" & vbCrLf &
"row 36" & vbCrLf &
"row 37" & vbCrLf &
"row 38" & vbCrLf &
"row 39" & vbCrLf &
"row 40" & vbCrLf &
"row 41" & vbCrLf &
"row 42" & vbCrLf &
"row 43" & vbCrLf &
"row 44" & vbCrLf &
"row 45" & vbCrLf &
"row 46" & vbCrLf &
"row 47" & vbCrLf &
"row 48" & vbCrLf &
"row 49" & vbCrLf &
"row 50" & vbCrLf &
"row 51" & vbCrLf &
"row 52" & vbCrLf &
"row 53" & vbCrLf &
"row 54" & vbCrLf &
"row 55" & vbCrLf &
"row 56" & vbCrLf &
"row 57" & vbCrLf &
"row 58" & vbCrLf &
"row 59" & vbCrLf &
"row 60" & vbCrLf &
"row 61" & vbCrLf &
"row 62" & vbCrLf &
"row 63" & vbCrLf &
"row 64" & vbCrLf &
"row 65" & vbCrLf &
"row 66" & vbCrLf &
"row 67" & vbCrLf &
"row 68" & vbCrLf &
"row 69" & vbCrLf &
"row 70" & vbCrLf &
"row 71" & vbCrLf &
"row 72" & vbCrLf &
"row 73" & vbCrLf &
"row 74" & vbCrLf &
"row 75" & vbCrLf &
"row 76" & vbCrLf &
"row 77" & vbCrLf &
"row 78" & vbCrLf &
"row 79" & vbCrLf &
"row 80" & vbCrLf &
"row 81" & vbCrLf &
"row 82" & vbCrLf &
"row 83" & vbCrLf &
"row 84" & vbCrLf &
"row 85" & vbCrLf &
"row 86" & vbCrLf &
"row 87" & vbCrLf &
"row 88" & vbCrLf &
"row 89" & vbCrLf &
"row 90" & vbCrLf &
"row 91" & vbCrLf &
"row 92" & vbCrLf &
"row 93" & vbCrLf &
"row 94" & vbCrLf &
"row 95" & vbCrLf &
"row 96" & vbCrLf &
"row 97" & vbCrLf &
"row 98" & vbCrLf &
"row 99" & vbCrLf &
"row 100" & vbCrLf &
"row 101" & vbCrLf &
"row 102" & vbCrLf &
"row 103" & vbCrLf &
"row 104" & vbCrLf &
"row 105" & vbCrLf &
"row 106" & vbCrLf &
"row 107" & vbCrLf &
"row 108" & vbCrLf &
"row 109" & vbCrLf &
"row 110" & vbCrLf &
"row 111" & vbCrLf &
"row 112" & vbCrLf &
"row 113" & vbCrLf &
"row 114" & vbCrLf &
"row 115" & vbCrLf &
"row 116" & vbCrLf &
"row 117" & vbCrLf &
"row 118" & vbCrLf &
"row 119" & vbCrLf &
"row 120" & vbCrLf &
"row 121" & vbCrLf &
"row 122" & vbCrLf &
"row 123" & vbCrLf &
"row 124" & vbCrLf &
"row 125" & vbCrLf &
"row 126" & vbCrLf &
"row 127" & vbCrLf &
"row 128" & vbCrLf &
"row 129" & vbCrLf &
"row 130" & vbCrLf &
"row 131" & vbCrLf &
"row 132" & vbCrLf &
"row 133" & vbCrLf &
"row 134" & vbCrLf &
"row 135" & vbCrLf &
"row 136" & vbCrLf &
"row 137" & vbCrLf &
"row 138" & vbCrLf &
"row 139" & vbCrLf &
"row 140" & vbCrLf &
"row 141" & vbCrLf &
"row 142" & vbCrLf &
"row 143" & vbCrLf &
"row 144" & vbCrLf &
"row 145" & vbCrLf &
"row 146" & vbCrLf &
"row 147" & vbCrLf &
"row 148" & vbCrLf &
"row 149" & vbCrLf &
"row 150"`

this causes VisualStudio to stackoverflow

**Comment by GrahamTheCoder** [comment] 2023-09-22 16:23
Thanks for digging into this. The fundamental pattern the converter uses is to recurse down the syntax tree structure, and each term concatenated together in your example is another layer of depth to that tree. The only other time I've seen this happen was also for a binary expression, so it could be worth trying to create a fix for this, even if the fix is merely to abort for that expression rather than let a StackOverflowException happen which will always kill the process.

**Closed** 2023-10-27 00:22 UTC
