### ISSUE TITLE
VB -> C#: CONVERSION ERROR: Conversion for OnErrorResumeNextStatement not implemented

### ISSUE THREAD

**Issue by elmagekmosaad** [icsharpcode/CodeConverter#1029] opened 2023-08-07 17:36 UTC
### VB.Net input code
```vbnet
If relevant, please enter some example VB.NET code here to reproduce the issue, or the steps taken to cause the issue.
`Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        On Error Resume Next
        Dim SaveFileDialog As SaveFileDialog = New SaveFileDialog
        Dim i As Integer
        SaveFileDialog.Title = "Save List.txt"
        SaveFileDialog.Filter = "List.txt File (*.txt)|*.txt"
        If SaveFileDialog.ShowDialog = DialogResult.OK Then
            Dim s As New IO.StreamWriter(SaveFileDialog.FileName, True)
            For i = 0 To ListBox1.Items.Count - 1
                s.WriteLine(ListBox1.Items.Item(i))
            Next
            s.Close()
            mginvoke(New Action(Sub() note.msg(str.str24)))
        End If
    End Sub`



simplification has errors: 
    CONVERSION ERROR: Conversion for OnErrorResumeNextStatement not implemented, please report this issue in 'On Error Resume Next' at character 2593

**Comment by GrahamTheCoder** [comment] 2023-08-10 21:10
Hi, thanks for getting in touch. I'll close this as a duplicate of https://github.com/icsharpcode/CodeConverter/issues/426, but I'd be interested to know what your ideal behaviour would be in this scenario.

e.g. We could add a catch block and put a warning inside, then link to a page explaining how to add error handling in C#:
Ideally to handle specific exceptions with try blocks that are as small and targeted as possible, or to check for an issue that would cause an exception up front

```csharp
private void Button3_Click(object sender, EventArgs e)
{
    try
    {
        var SaveFileDialog = new SaveFileDialog();
        int i;
        SaveFileDialog.Title = "Save List.txt";
        SaveFileDialog.Filter = "List.txt File (*.txt)|*.txt";
        if (SaveFileDialog.ShowDialog == DialogResult.OK)
        {
            var s = new StreamWriter(SaveFileDialog.FileName, true);
            var loopTo = ListBox1.Items.Count - 1;
            for (i = 0; i <= loopTo; i++)
                s.WriteLine(ListBox1.Items.Item(i));
            s.Close();
            mginvoke(new Action(() => note.msg(Conversion.str.str24)));
        }
    }
    catch (Exception e)
    {
        #warning Conversion issue: "On Error Resume Next" removed, please add error handling here
        // See https://github.com/icsharpcode/CodeConverter/wiki/OnErrorResumeNext for more information
    }
}
```

**Closed by GrahamTheCoder** 2023-08-10 21:10 UTC
Labels: duplicate, VB -> C#
